name: Run Scraper Script

on:
  schedule:
    # This cron expression runs the job every day at 6 AM to 10 AM SAST (UTC +2)
    - cron: "0 6-13 * * *"  # Runs at 6, 7, 8, 9, 10 AM SAST

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Firebase service account
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" | base64 --decode > $HOME/serviceAccountKey.json
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_AUTH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper script
        run: |
          python scraper.py
